package br.edu.cederj.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.*;

/**
 * GerDisciplina generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ger_disciplina")
public class Disciplina implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)	
	private Long id;

	@Column(name = "sigla", nullable = false, length = 1)
	@Pattern(regexp="^[A-Z]{1,1}$", message="Deve ser apenas uma letra maiúscula.")
	private String sigla;

	@Column(name = "nome", nullable = false, length = 30)
	@Length(max=30,min=3,message="Deve ter entre 3 e 30 caracteres.")	
	private String nome;

	@Column(name = "ativo")
	private boolean ativo;
	
	@OneToMany(mappedBy = "disciplina", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private List<Vaga> vaga = new ArrayList<Vaga>();



	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	public List<Vaga> getVaga() {
		return vaga;
	}

	public void setVaga(List<Vaga> vaga) {
		this.vaga = vaga;
	}

	

}
